shinyUI(fluidPage(
  theme = "try.css",
  navbarPage(
    # title="",
    # inverse = TRUE,
    tags$hr(),
    ##-- Title Header ----
    tags$div(
      div(img(src="GSACENTRAL_Logo.png", width = "100px", height = "50px"),
              style = "padding-left:5px;"),
      class = "text-center",
      span(strong(h2("GSARefDB - The Gene Set Analysis Reference Database")),
           style = "color:steelblue")),
    tags$hr(),
    tabPanel(strong(h5("General Methods and Tools")),
             # Download Button
             # downloadButton('downloadData', 'Download'),
             DT::dataTableOutput("DT1")),
    tabPanel(h5("Reviews and Benchmarks"),
             DT::dataTableOutput("DT2")),
    tabPanel(h5("Genomic GSA"),
            DT::dataTableOutput("DT3")),
    tabPanel(h5("ncRNA GSA"),
             DT::dataTableOutput("DT4")),
    tabPanel(h5("MS-based GSA"),
             DT::dataTableOutput("DT5")),
    tabPanel(h5("Metagenomics GSA"),
             DT::dataTableOutput("DT6")),
    tabPanel(h5("Integromics GSA"),
             DT::dataTableOutput("DT7")),
    tabPanel(h5("DB Statistics"),
             shiny::plotOutput("plot", width = "100%", height = "1000px")),
    tabPanel(h5("Citation History"),
             DT::dataTableOutput("DT8")),
    tabPanel(h5("Archive"), 
             includeMarkdown("www/files/Archive.md")),
    tabPanel(h5("FAQs"), 
             includeMarkdown("www/files/FAQs.md")),
    selected = strong(h5("General Methods and Tools")),
    tags$hr(),
    footer = tags$div(
      div(img(src="GSACENTRAL_Logo.png", width = "100px", height = "50px"),
              style = "padding-left:5px;"),
      class = "text-center",
      span(strong(h4("GSARefDB v1.5. Last updated: March 24th, 2021")),
           style = "color:gray")))
))
